# Installs the necessary packages on the target host

- name: Install packages on the host
  apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
  loop:
    - uwsgi
    - acl
    - unzip

- name: Install python3 packages on the host
  apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
  loop:
    - uwsgi-plugin-python3
    - python3
    - python3-pip
    - python3-venv

- block:
  - name: Install Apache on the host
    apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
    loop:
      - apache2
      - libapache2-mod-uwsgi

  - name: Enable Apache uWSGI module
    apache2_module: state=present name=uwsgi

  - name: Enable Apache module (mod-ssl)
    apache2_module: state=present name=ssl

  - name: Enable Apache uWSGI module (mod-uwsgi)
    apache2_module: state=present name=uwsgi

  - name: Enable Apache module (mod-rewrite)
    apache2_module: state=present name=rewrite

  - name: Enable Apache module (mod-proxy)
    apache2_module: state=present name=proxy

  when: webserver=='apache2'

- name: Install NGinx on the host
  apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
  loop:
    - nginx
  when: webserver=='nginx'

- name: Install PostgreSQL on the host
  apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
  loop:
    - python3-psycopg2
    - postgresql
    - postgresql-contrib
    - libpq-dev
  when: database=='postgresql'

- name: Install additional packages on the host
  apt: name="{{ item }}" update_cache=yes state=present cache_valid_time=3600
  loop: "{{ host_additional_packages }}"
